### ISSUE TITLE
Wrong hotkey

### ISSUE THREAD

**Issue by skovtur** [StefanBRas/ankiextractoR#3]
line 59 in README.md says:
[...] Manage Note Types (ctrl + shift + a)

When I use Anki it is (ctrl + shift + n)
![wrong_hotkey_1](https://user-images.githubusercontent.com/35959339/97777986-25d7fb80-1b74-11eb-9d4f-1209efa4ecf9.png)

I have an old version of anki and have not been able to test in other.
Hot keys are not listed in the official documentation for Anki.
But this link with hot keys also says it is (ctrl + shift + n):
https://productivityforge.com/the-most-useful-anki-keyboard-shortcuts/

**Comment by StefanBRas** [comment]
Good catch! You can make a pull request with a fix
@skovtur
